name: ci-development
run-name: ${{ github.actor }} is running CI 🚀
on:
  push:
    branches:
      - 'main'
      - 'develop'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  MONGO_INITDB_ROOT_USERNAME: ci_development_username
  MONGO_INITDB_ROOT_PASSWORD: ci_development_password
  DATABASE_URL_CONNECTION: mongodb://ci_development_username:ci_development_password@localhost:27017/product?authSource=admin
  REDIS_PORT: 6379
  REDIS_HOST: localhost
  REDIS_PASSWORD: ci_development_redis_password
  JWT_SECRET: ci_development_jwt_secret
  JWT_EXPIRATION: 1h
jobs:
  checking:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [20.x]
        
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          REDIS_PASSWORD: ci_development_redis_password
          REDIS_PORT: 6379
          
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: ci_development_username
          MONGO_INITDB_ROOT_PASSWORD: ci_development_password
        ports:
            - '27017:27017'
        options: >-
          --health-cmd "echo 'db.runCommand("ping").ok' | mongosh --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Copy repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Check lint
        run: yarn lint

      - name: Check format
        run: yarn format

      - name: Build project
        run: yarn build

      - name: Run Coverage Tests
        run: yarn test:cov

      - name: Run Integration Tests
        run: yarn test:e2e --force-exit
